models/Professor.php
<?php

namespace app\models;

use app\components\helpers\OIB;
use Yii;

/**
 * This is the model class for table "professor".
 *
 * @property int $id
 * @property int $oib
 * @property string $name
 * @property string $surname
 * @property string $address
 * @property int $post
 * @property string $location
 * @property string date_of_birth
 *
 * @property Exam[] $exams
 * @property ProfessorSubjectLink[] $professorSubjectLinks
 * @property Subject[] $subjects
 */
class Professor extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'professor';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['oib', 'name', 'surname'], 'required'],
            [['oib', 'post'], 'integer'],
            [['oib'],'checkOib'],
            [['oib'],'string','min'=>11,'max'=>11],
            [['date_of_birth', 'fullname'], 'safe'],
            [['name', 'surname', 'address', 'location'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'oib' => 'Oib',
            'name' => 'Name',
            'surname' => 'Surname',
            'address' => 'Address',
            'post' => 'Post',
            'location' => 'Location',
            'date_of_birth' => 'Date of birth',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExams()
    {
        return $this->hasMany(Exam::className(), ['professor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfessorSubjectLinks()
    {
        return $this->hasMany(ProfessorSubjectLink::className(), ['professor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubjects()
    {
        return $this->hasMany(Subject::className(), ['id' => 'subject_id'])->viaTable('professor_subject_link', ['professor_id' => 'id']);
    }

    public function checkOib()
    {
        if (!OIB::check($this->oib)) {
            $this->addError('oib', 'OIB is no good');
        }

    }

    public function beforeSave($insert) {
        if($this->date_of_birth){
            $this->date_of_birth = Yii::$app->formatter->asDate(strtotime($this->date_of_birth), "php:Y-m-d");
        }
        return parent::beforeSave($insert);
    }

    public function getFullName() {
        return $this->name . " " . $this->surname;
    }
}

controllers/ProfessorController.php
<?php

namespace app\controllers;

use app\models\ProfessorSubjectLink;
use app\models\SearchProfessorSubjectLink;
use app\models\Subject;
use Yii;
use app\models\Professor;
use app\models\SearchProfessor;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProfessorController implements the CRUD actions for Professor model.
 */
class ProfessorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Professor models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchProfessor();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Professor model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Professor model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Professor();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'subjects' => Subject::find()->all()
        ]);
    }

    /**
     * Updates an existing Professor model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Professor model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDeleteSubject()
    {
        $profSubjLink = ProfessorSubjectLink::findOne([
            'professor_id' => Yii::$app->request->get('professor_id'),
            'subject_id' => Yii::$app->request->get('subject_id')]
        );

        $profSubjLink->delete();

        return $this->redirect(['view', 'id' => Yii::$app->request->get('professor_id')]);
    }

    /**
     * Finds the Professor model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Professor the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Professor::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ProfessorSubjectLinkController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ProfessorSubjectLink;
use app\models\SearchProfessorSubjectLink;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProfessorSubjectLinkController implements the CRUD actions for ProfessorSubjectLink model.
 */
class ProfessorSubjectLinkController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ProfessorSubjectLink models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchProfessorSubjectLink();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProfessorSubjectLink model.
     * @param integer $professor_id
     * @param integer $subject_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($professor_id, $subject_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($professor_id, $subject_id),
        ]);
    }

    /**
     * Creates a new ProfessorSubjectLink model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProfessorSubjectLink();

        $professor_id = Yii::$app->request->get('professor_id');
        $subject_id = Yii::$app->request->get('subject_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (isset($professor_id)) {
                return $this->redirect(['professor/view', 'id' => $model->professor_id]);
            } else if (isset($subject_id)) {
                return $this->redirect(['subject/view', 'id' => $model->subject_id]);
            }

            return $this->redirect(['view', 'professor_id' => $model->professor_id, 'subject_id' => $model->subject_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ProfessorSubjectLink model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $professor_id
     * @param integer $subject_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($professor_id, $subject_id)
    {
        $model = $this->findModel($professor_id, $subject_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'professor_id' => $model->professor_id, 'subject_id' => $model->subject_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ProfessorSubjectLink model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $professor_id
     * @param integer $subject_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($professor_id, $subject_id)
    {
        $this->findModel($professor_id, $subject_id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProfessorSubjectLink model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $professor_id
     * @param integer $subject_id
     * @return ProfessorSubjectLink the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($professor_id, $subject_id)
    {
        if (($model = ProfessorSubjectLink::findOne(['professor_id' => $professor_id, 'subject_id' => $subject_id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/professor/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Professor */
/* @var $form yii\widgets\ActiveForm */
/* @var $update boolean */
?>

<div class="professor-form">

    <?php $form = ActiveForm::begin([
        'id' => 'dynamic-form',
        'enableClientValidation' => true
    ]); ?>

    <?= $form->field($model, 'oib')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'post')->textInput() ?>

    <?= $form->field($model, 'location')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_of_birth')->widget(\yii\jui\DatePicker::class, [
        'value' => date('Y-m-d'),
        'dateFormat' => 'dd-MM-yyyy',
    ]) ?>

    <?php
    $dataProvider = new \yii\data\ActiveDataProvider([
        'query' => $model->getProfessorSubjectLinks(),
        'pagination' => [
            'pageSize' => 20,
        ],
    ]);
    if($update) {

        echo \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                [
                    'attribute' => 'subject.name',
                    'label' => 'Subject'
                ],
                'subject.ects_points',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'header'=>'Actions',
                    'template' => '{delete}',
                    'buttons' => [
                        'delete' => function ($url) {
                            return Html::a('<span class="glyphicon glyphicon-ban-circle"></span>', $url, [
                                'title' => Yii::t('app', 'Delete'),
                                'data-confirm' => Yii::t('yii', 'Are you sure you want to delete?'),
                                'data-method' => 'post', 'data-pjax' => '0',
                            ]);
                        }

                    ],
                    'urlCreator' => function ($action, $model) {
                        if ($action === 'delete') {
                            $url = Url::to(['professor/delete-subject', 'subject_id' => $model->subject->id, 'professor_id' => $model->professor->id ]);
                            return $url;
                        }
                    }
                ]
            ],
        ]);
    }
    ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        <?= ($update) ? Html::a('Add subject', ['/professor-subject-link/create', 'professor_id' => $model->id], ['class' => 'btn btn-primary']) : false; ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/professor/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SearchProfessor */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="professor-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'oib') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'post') ?>

    <?php // echo $form->field($model, 'location') ?>

    <?php // echo $form->field($model, 'date_of_birth') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/professor/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Professor */
/* @var $subjects app\models\Subjects */

/* @var $subjects app\models\Subject */

$this->title = 'Create Professor';
$this->params['breadcrumbs'][] = ['label' => 'Professors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="professor-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
        'update' => false
    ]) ?>

</div>

views/professor/index.php
<?php

use yii\grid\DataColumn;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\jui\AutoComplete;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchProfessor */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Professors';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="professor-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Professor', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'oib',
            [
                "class" => yii\grid\DataColumn::className(),
                "attribute" => "fullname",
                'filter' => AutoComplete::widget([
                    'model' => $searchModel,
                    'attribute' => 'fullname',
                    'clientOptions' => [
                        'source' => \app\models\Professor::find()->select(['concat(name, " ", surname) AS value', 'concat(name, " ", surname) AS label'])->orderBy('name')->asArray()->all(),
                    ],
                    'options' => ['class' => 'form-control'],
                ]),
                'value' => function ($model) {
                    return $model->getFullName();
                },
                "format" => "raw",
                'label' => "Professor",

            ],
            'address',
            [
                'label' => 'Subjects',
                'value' => function ($model)
                {
                    return implode(', ', $model->getSubjects()->select('name')->column());
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/professor/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Professor */
/* @var $subjects app\models\Subject */

$this->title = 'Update Professor: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Professors', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="professor-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'update' => true
    ]) ?>

</div>

views/professor/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Professor */

$this->title = $model->getFullName();
$this->params['breadcrumbs'][] = ['label' => 'Professors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

?>
<div class="professor-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Add subject', ['/professor-subject-link/create', 'professor_id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'oib',
            'name',
            'surname',
            'address',
            'post',
            'location',
            'date_of_birth',
            [
                'label' => 'Subjects',
                'value' => function ($model)
                    {
                        return implode(', ', $model->getSubjects()->select('name')->column());
                    }
            ],
        ],
    ]) ?>

</div>